"""Fabric Data Product Framework package."""

from .fabric_notebook import (
    Housepath,
    ODI_METADATA_LOGGER,
    add_system_technical_columns,
    check_naming_convention,
    clean_datetime_columns,
    get_path,
    load_fabric_config,
    lakehouse_csv_read,
    lakehouse_excel_read_as_spark,
    lakehouse_parquet_read_as_spark,
    lakehouse_table_read,
    lakehouse_table_write,
    pass_if_yes_else_run,
    transformation_reasons,
    transformation_summary,
    warehouse_read,
    warehouse_write,
)
from .template_generator import create_pipeline_notebook_template
from .dq import (
    build_dq_rule_records,
    generate_dq_rule_candidates,
    generate_dq_rule_candidates_with_fabric_ai,
    load_dq_rules,
    normalize_dq_rule,
    normalize_dq_rules,
    run_dq_rules,
    run_dq_workflow,
    store_dq_rules,
from .drift_checkers import (
    build_and_write_partition_snapshot,
    build_and_write_schema_snapshot,
    check_partition_drift,
    check_profile_drift,
    check_schema_drift,
    load_latest_partition_snapshot,
    load_latest_schema_snapshot,
    summarize_drift_results,
)

from .governance_classifier import (
    build_governance_classification_records,
    classify_column,
    classify_columns,
    summarize_governance_classifications,
    write_governance_classifications,
)
from .data_contract import (
    DataProductContract,
    DriftContract,
    GovernanceContract,
    MetadataContract,
    QualityContract,
    RuntimeContract,
    SourceContract,
    TargetContract,
    assert_data_product_passed,
    build_drift_contract,
    build_governance_contract,
    build_metadata_contract,
    build_quality_contract,
    build_runtime_context_from_contract,
    build_runtime_contract,
    build_source_contract,
    build_target_contract,
    data_product_contract_to_dict,
    load_data_contract,
    normalize_data_product_contract,
    run_data_product,
    validate_data_contract_shape,
)

__version__ = "0.1.0"

__all__ = [
    "Housepath",
    "get_path",
    "load_fabric_config",
    "lakehouse_table_read",
    "lakehouse_table_write",
    "lakehouse_csv_read",
    "lakehouse_parquet_read_as_spark",
    "lakehouse_excel_read_as_spark",
    "warehouse_read",
    "warehouse_write",
    "check_naming_convention",
    "clean_datetime_columns",
    "add_system_technical_columns",
    "ODI_METADATA_LOGGER",
    "transformation_summary",
    "transformation_reasons",
    "pass_if_yes_else_run",
    "create_pipeline_notebook_template",    "run_dq_workflow",
    "run_dq_rules",
    "load_dq_rules",
    "store_dq_rules",
    "build_dq_rule_records",
    "normalize_dq_rules",
    "normalize_dq_rule",
    "generate_dq_rule_candidates",
    "generate_dq_rule_candidates_with_fabric_ai",
    "classify_column",
    "classify_columns",
    "build_governance_classification_records",
    "write_governance_classifications",
    "summarize_governance_classifications",
    "SourceContract",
    "TargetContract",
    "QualityContract",
    "DriftContract",
    "GovernanceContract",
    "MetadataContract",
    "RuntimeContract",
    "DataProductContract",
    "build_source_contract",
    "build_target_contract",
    "build_quality_contract",
    "build_drift_contract",
    "build_governance_contract",
    "build_metadata_contract",
    "build_runtime_contract",
    "normalize_data_product_contract",
    "data_product_contract_to_dict",
    "assert_data_product_passed",
    "build_runtime_context_from_contract",
    "load_data_contract",
    "run_data_product",
    "validate_data_contract_shape",
    "check_schema_drift",
    "build_and_write_schema_snapshot",
    "load_latest_schema_snapshot",
    "check_partition_drift",
    "build_and_write_partition_snapshot",
    "load_latest_partition_snapshot",
    "check_profile_drift",
    "summarize_drift_results",
]
