"""Public notebook-friendly entrypoints for the FabricOps Starter Kit."""

from .drift import check_partition_drift, check_profile_drift, check_schema_drift, summarize_drift_results
from .config import (
    bootstrap_fabric_env,
    check_fabric_ai_functions_available,
    get_path,
    run_config_smoke_tests,
    validate_framework_config,
)
from .fabric_io import (
    Housepath,
    lakehouse_csv_read,
    lakehouse_excel_read_as_spark,
    lakehouse_parquet_read_as_spark,
    lakehouse_table_read,
    lakehouse_table_write,
    load_fabric_config,
    warehouse_read,
    warehouse_write,
    seed_minimal_sample_source_table,
)
from .lineage import (
    build_lineage_from_notebook_code,
    build_lineage_handover_markdown,
    build_lineage_record_from_steps,
    build_lineage_records,
    enrich_lineage_steps_with_ai,
    fallback_copilot_lineage_prompt,
    plot_lineage_steps,
    scan_notebook_cells,
    scan_notebook_lineage,
    validate_lineage_steps,
)
from .governance import (
    build_governance_classification_records,
    classify_column,
    classify_columns,
    summarize_governance_classifications,
    write_governance_classifications,
)
from .contracts import (
    build_contract_column_records,
    build_contract_header_record,
    build_contract_records,
    build_contract_rule_records,
    build_contract_summary,
    contract_records_to_spark,
    extract_business_keys,
    extract_classifications,
    extract_optional_columns,
    extract_quality_rules,
    extract_required_columns,
    get_executable_quality_rules,
    load_contract_from_lakehouse,
    load_latest_approved_contract,
    normalize_contract_dict,
    validate_contract_dict,
    write_contract_to_lakehouse,
)

from .metadata import (
    build_dataset_run_record,
    build_quality_result_records,
    build_schema_drift_records,
    build_schema_snapshot_records,
    write_metadata_records,
    write_multiple_metadata_outputs,
)
from .profiling import (
    build_ai_quality_context,
    profile_dataframe,
    profile_dataframe_to_metadata,
    profile_metadata_to_records,
    generate_metadata_profile,
)
from .ai import (
    build_dq_rule_candidate_prompt,
    build_governance_candidate_prompt,
    build_handover_summary_prompt,
    build_manual_dq_rule_prompt_package,
    build_manual_governance_prompt_package,
    build_manual_handover_prompt_package,
    configure_fabric_ai_functions,
    generate_dq_rule_candidates_with_fabric_ai,
    generate_governance_candidates_with_fabric_ai,
    generate_handover_summary_with_fabric_ai,
    parse_manual_ai_json_response,
)
from .quality import load_data_contract, run_data_product, run_quality_rules

from .dq import (
    AI_SUGGESTABLE_DQ_RULE_TYPES,
    profile_for_dq,
    suggest_dq_rules,
    extract_dq_rules,
    validate_dq_rules,
    build_dq_rule_history,
    build_dq_rule_deactivations,
    load_active_dq_rules,
    _load_active_dq_rule_metadata,
    split_dq_rows,
    run_dq_rules,
    assert_dq_passed,
)
from .dq_review import review_dq_rules, review_dq_rule_deactivations
from .run_summary import build_run_summary, render_run_summary_markdown
from .runtime import assert_notebook_name_valid, build_runtime_context, generate_run_id, validate_notebook_name
from .technical_columns import add_audit_columns, add_datetime_features, add_hash_columns, default_technical_columns

__version__ = "0.1.0"

__all__ = [
    "review_dq_rule_deactivations",
    "review_dq_rules",
    "load_active_dq_rules",
    "build_dq_rule_deactivations",
    "build_dq_rule_history",
    "split_dq_rows",
    "extract_dq_rules",
    "suggest_dq_rules",
    "profile_for_dq",
    "AI_SUGGESTABLE_DQ_RULE_TYPES",
    "Housepath",
    "validate_framework_config",
    "bootstrap_fabric_env",
    "run_config_smoke_tests",
    "check_fabric_ai_functions_available",
    "load_fabric_config",
    "get_path",
    "lakehouse_table_read",
    "lakehouse_table_write",
    "lakehouse_csv_read",
    "lakehouse_parquet_read_as_spark",
    "lakehouse_excel_read_as_spark",
    "warehouse_read",
    "warehouse_write",
    "seed_minimal_sample_source_table",
    "generate_run_id",
    "build_runtime_context",
    "validate_notebook_name",
    "assert_notebook_name_valid",
    "profile_dataframe",
    "profile_dataframe_to_metadata",
    "profile_metadata_to_records",
    "generate_metadata_profile",
    "build_ai_quality_context",
    "run_quality_rules",
    "run_dq_rules",
    "assert_dq_passed",
    "validate_dq_rules",
    "parse_manual_ai_json_response",
    "build_manual_handover_prompt_package",
    "build_manual_governance_prompt_package",
    "build_manual_dq_rule_prompt_package",
    "build_handover_summary_prompt",
    "build_governance_candidate_prompt",
    "build_dq_rule_candidate_prompt",
    "configure_fabric_ai_functions",
    "generate_dq_rule_candidates_with_fabric_ai",
    "generate_governance_candidates_with_fabric_ai",
    "generate_handover_summary_with_fabric_ai",
    "check_schema_drift",
    "check_partition_drift",
    "check_profile_drift",
    "summarize_drift_results",
    "classify_column",
    "classify_columns",
    "build_governance_classification_records",
    "write_governance_classifications",
    "summarize_governance_classifications",
    "build_lineage_records",
    "scan_notebook_lineage",
    "scan_notebook_cells",
    "enrich_lineage_steps_with_ai",
    "fallback_copilot_lineage_prompt",
    "validate_lineage_steps",
    "build_lineage_record_from_steps",
    "build_lineage_from_notebook_code",
    "build_lineage_handover_markdown",
    "plot_lineage_steps",
    "build_run_summary",
    "render_run_summary_markdown",
    "build_dataset_run_record",
    "build_schema_snapshot_records",
    "build_schema_drift_records",
    "build_quality_result_records",
    "write_metadata_records",
    "write_multiple_metadata_outputs",
    "load_data_contract",
    "run_data_product",
    "default_technical_columns",
    "add_datetime_features",
    "add_audit_columns",
    "add_hash_columns",
    "normalize_contract_dict",
    "validate_contract_dict",
    "build_contract_header_record",
    "build_contract_column_records",
    "build_contract_rule_records",
    "build_contract_records",
    "contract_records_to_spark",
    "write_contract_to_lakehouse",
    "load_contract_from_lakehouse",
    "load_latest_approved_contract",
    "extract_required_columns",
    "extract_optional_columns",
    "extract_business_keys",
    "extract_classifications",
    "extract_quality_rules",
    "get_executable_quality_rules",
    "build_contract_summary",
]
