"""Metadata registry for generated public API documentation."""

from __future__ import annotations

from typing import NotRequired, TypedDict


class PublicSymbolDocMetadata(TypedDict):
    """Documentation metadata for a public symbol exported in ``__all__``."""

    symbol_name: str
    module: str
    kind: str
    workflow_step: int | str | None
    importance: NotRequired[str]
    purpose: NotRequired[str]
    summary_override: str | None


WORKFLOW_STEP_DOCS: list[dict[str, int | str]] = [
    {"number": 1, "slug": "step-01-governance-context", "title": "Governance context", "subtext": "This step captures the governance context: approved usage, owner, and data agreement. The agreement may live outside Fabric, such as in SharePoint documents. Functions in this step mainly link notebooks back to that agreement so the technical work stays tied to the approved business context."},
    {"number": "2A", "slug": "step-02a-shared-runtime-config", "title": "Create shared runtime config", "subtext": "This step creates the shared config that other notebooks depend on, including environment paths, workspace targets, AI availability, and standard naming rules. The goal is to define the project setup once so exploration and pipeline notebooks do not repeat hidden manual configuration."},
    {"number": "2B", "slug": "step-02b-notebook-startup-checks", "title": "Run notebook startup checks", "subtext": "This step runs the startup utility or smoke test at the beginning of every exploration and pipeline notebook. The goal is to confirm the notebook is running in the expected environment, follows naming rules, and has the required Fabric or AI capabilities before any data work begins."},
    {"number": 3, "slug": "step-03-source-contract-ingestion-pattern", "title": "Define source contract & ingestion pattern", "subtext": "This step defines the contract between the upstream source and this notebook. It captures what data is expected, including schema, data types, update frequency, update method, watermark column, and whether the source is append only, overwritten, or slowly changing. Functions in this step help the pipeline decide how to ingest, validate, snapshot, or incrementally process the source data."},
    {"number": 4, "slug": "step-04-ingest-profile-store", "title": "Ingest, profile & store source data", "subtext": "This step brings the source data into the framework, profiles it, and stores it for later use. Functions in this step focus on reading the data, capturing basic profiling results, and saving the raw or source-aligned version before business transformation begins."},
    {"number": 5, "slug": "step-05-explore-transform-logic", "title": "Explore data & explain transformation logic", "subtext": "This step is where the analyst studies the profiled source data and explains why transformation is needed. There may not be many helper functions here today, but future functions could support standard EDA, AI assisted analysis, and documentation of business assumptions before the logic becomes part of the repeatable pipeline."},
    {"number": "6A", "slug": "step-06a-transformation-logic", "title": "Write transformation logic", "subtext": "This step contains the main transformation logic that converts source-aligned data into the target output. Functions here support reusable pipeline code so the same logic can run consistently during development, testing, and scheduled refresh."},
    {"number": "6B", "slug": "step-06b-runtime-standards", "title": "Apply runtime standards", "subtext": "This step applies standard runtime requirements such as technical columns, run IDs, timestamps, partition keys, and other repeatable conventions. Functions here make outputs easier to audit, troubleshoot, join back to pipeline runs, and operate at scale."},
    {"number": "6C", "slug": "step-06c-pipeline-controls", "title": "Enforce pipeline controls", "subtext": "This step enforces the controls that decide whether the pipeline output should be trusted. Functions here support data quality rules, schema checks, classification checks, and other contract validations before data is released downstream."},
    {"number": "6D", "slug": "step-06d-controlled-outputs", "title": "Write controlled outputs", "subtext": "This step writes the transformed output to the correct lakehouse, warehouse, or product layer. Functions here make the write pattern explicit, repeatable, and aligned to the intended environment instead of relying on ad hoc exports."},
    {"number": 7, "slug": "step-07-output-profile-product-contract", "title": "Profile output & publish product contract", "subtext": "This step profiles the created output, stores its metadata, and creates the data contract for the next notebook, pipeline, or consumer. Functions here help record what was produced, write the evidence to metadata tables or catalogues, and make the output understandable and reusable downstream."},
    {"number": 8, "slug": "step-08-ai-assisted-dq-suggestions", "title": "Suggest AI assisted data quality rules", "subtext": "This step uses AI in exploration notebooks to suggest possible data quality rules from profiling results, business context, and source knowledge. These AI functions are only advisory. The actual rule creation, approval, and enforcement must still be done by the human engineer in the pipeline notebook."},
    {"number": 9, "slug": "step-09-ai-assisted-classification", "title": "Suggest AI assisted column classification", "subtext": "This step uses AI in exploration notebooks to suggest column classifications such as PII, sensitivity level, and governance labels for the planned output. These AI functions are only advisory. The actual label assignment must be approved by governance or data stewards and enforced by the human engineer in the pipeline notebook."},
    {"number": 10, "slug": "step-10-lineage-handover-documentation", "title": "Generate lineage & handover documentation", "subtext": "This step creates the final documentation needed for review, handover, and future maintenance. Functions here support lineage, transformation summaries, and handover notes so another analyst or engineer can understand what was built, why it was built, and how to operate it."},
]

PUBLIC_SYMBOL_DOCS: list[PublicSymbolDocMetadata] = [
    {"symbol_name": "Housepath", "module": "fabric_input_output", "kind": "class", "workflow_step": "2A", "summary_override": None},
    {"symbol_name": "create_path_config", "module": "environment_config", "kind": "function", "workflow_step": "2A", "summary_override": None},
    {"symbol_name": "create_notebook_runtime_config", "module": "environment_config", "kind": "function", "workflow_step": "2A", "summary_override": None},
    {"symbol_name": "create_ai_prompt_config", "module": "environment_config", "kind": "function", "workflow_step": "2A", "summary_override": None},
    {"symbol_name": "create_quality_config", "module": "environment_config", "kind": "function", "workflow_step": "2A", "summary_override": None},
    {"symbol_name": "create_governance_config", "module": "environment_config", "kind": "function", "workflow_step": "2A", "summary_override": None},
    {"symbol_name": "create_lineage_config", "module": "environment_config", "kind": "function", "workflow_step": "2A", "summary_override": None},
    {"symbol_name": "create_framework_config", "module": "environment_config", "kind": "function", "workflow_step": "2A", "summary_override": None},
    {"symbol_name": "validate_framework_config", "module": "environment_config", "kind": "function", "workflow_step": "2A", "summary_override": None},
    {
        "symbol_name": "run_config_smoke_tests",
        "module": "environment_config",
        "kind": "function",
        "workflow_step": "2B",
        "importance": "Essential",
        "purpose": "Run 00_env_config smoke checks for Spark, runtime context, configured paths, notebook naming, and optional AI/IO imports.",
        "summary_override": None,
    },
    {
        "symbol_name": "bootstrap_fabric_env",
        "module": "environment_config",
        "kind": "function",
        "workflow_step": "2B",
        "importance": "Essential",
        "purpose": "Bootstrap 00_env_config environment readiness by resolving required targets and collecting runtime/AI check results.",
        "summary_override": None,
    },
    {"symbol_name": "load_fabric_config", "module": "fabric_input_output", "kind": "function", "workflow_step": "2A", "summary_override": None},
    {"symbol_name": "get_path", "module": "environment_config", "kind": "function", "workflow_step": "2A", "summary_override": None},
    {"symbol_name": "lakehouse_table_read", "module": "fabric_input_output", "kind": "function", "workflow_step": 3, "summary_override": None},
    {"symbol_name": "lakehouse_table_write", "module": "fabric_input_output", "kind": "function", "workflow_step": "6D", "summary_override": None},
    {"symbol_name": "lakehouse_csv_read", "module": "fabric_input_output", "kind": "function", "workflow_step": 3, "summary_override": None},
    {"symbol_name": "lakehouse_parquet_read_as_spark", "module": "fabric_input_output", "kind": "function", "workflow_step": 3, "summary_override": None},
    {"symbol_name": "lakehouse_excel_read_as_spark", "module": "fabric_input_output", "kind": "function", "workflow_step": 3, "summary_override": None},
    {"symbol_name": "warehouse_read", "module": "fabric_input_output", "kind": "function", "workflow_step": 3, "summary_override": None},
    {"symbol_name": "warehouse_write", "module": "fabric_input_output", "kind": "function", "workflow_step": "6D", "summary_override": None},
    {"symbol_name": "generate_run_id", "module": "runtime_context", "kind": "function", "workflow_step": 1, "summary_override": None},
    {"symbol_name": "build_runtime_context", "module": "runtime_context", "kind": "function", "workflow_step": 1, "summary_override": None},
    {"symbol_name": "validate_notebook_name", "module": "runtime_context", "kind": "function", "workflow_step": 1, "summary_override": None},
    {"symbol_name": "assert_notebook_name_valid", "module": "runtime_context", "kind": "function", "workflow_step": 1, "summary_override": None},
    {"symbol_name": "profile_dataframe", "module": "data_profiling", "kind": "function", "workflow_step": 4, "summary_override": None},
    {"symbol_name": "profile_dataframe_to_metadata", "module": "data_profiling", "kind": "function", "workflow_step": 4, "summary_override": None},
    {"symbol_name": "profile_metadata_to_records", "module": "data_profiling", "kind": "function", "workflow_step": 4, "summary_override": None},
    {"symbol_name": "generate_metadata_profile", "module": "data_profiling", "kind": "function", "workflow_step": 4, "summary_override": None},
    {"symbol_name": "build_ai_quality_context", "module": "data_profiling", "kind": "function", "workflow_step": 4, "summary_override": None},
    {"symbol_name": "run_quality_rules", "module": "data_quality", "kind": "function", "workflow_step": "6C", "summary_override": None},
    {"symbol_name": "get_default_dq_rule_templates", "module": "data_quality", "kind": "function", "workflow_step": 8, "importance": "Optional", "summary_override": None},
    {"symbol_name": "DEFAULT_DQ_RULE_SUGGESTION_PROMPT_TEMPLATE", "module": "data_quality", "kind": "constant", "workflow_step": 8, "importance": "Optional", "summary_override": "Default prompt template used to draft candidate DQ rules."},
    {"symbol_name": "validate_dq_rules", "module": "data_quality", "kind": "function", "workflow_step": "6C", "importance": "Essential", "summary_override": None},
    {"symbol_name": "run_dq_rules", "module": "data_quality", "kind": "function", "workflow_step": "6C", "importance": "Essential", "summary_override": None},
    {"symbol_name": "assert_dq_passed", "module": "data_quality", "kind": "function", "workflow_step": "6D", "importance": "Essential", "summary_override": None},
    {"symbol_name": "split_valid_and_quarantine", "module": "data_quality", "kind": "function", "workflow_step": "6C", "importance": "Optional", "summary_override": None},
    {"symbol_name": "suggest_accepted_value_mapping_prompt", "module": "data_quality", "kind": "function", "workflow_step": 8, "importance": "Optional", "summary_override": None},
    {"symbol_name": "suggest_closest_accepted_value", "module": "data_quality", "kind": "function", "workflow_step": 8, "importance": "Optional", "summary_override": None},
    {"symbol_name": "suggest_dq_rules_prompt", "module": "data_quality", "kind": "function", "workflow_step": 8, "importance": "Optional", "summary_override": None},
    {"symbol_name": "check_fabric_ai_functions_available", "module": "environment_config", "kind": "function", "workflow_step": "2A", "summary_override": None},
    {"symbol_name": "build_dq_rule_candidate_prompt", "module": "data_quality", "kind": "function", "workflow_step": 8, "summary_override": None},
    {"symbol_name": "build_governance_candidate_prompt", "module": "data_governance", "kind": "function", "workflow_step": 9, "summary_override": None},
    {"symbol_name": "build_handover_summary_prompt", "module": "handover_documentation", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "build_manual_dq_rule_prompt_package", "module": "data_quality", "kind": "function", "workflow_step": 8, "summary_override": None},
    {"symbol_name": "build_manual_governance_prompt_package", "module": "data_governance", "kind": "function", "workflow_step": 9, "summary_override": None},
    {"symbol_name": "build_manual_handover_prompt_package", "module": "handover_documentation", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "parse_manual_ai_json_response", "module": "handover_documentation", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "configure_fabric_ai_functions", "module": "environment_config", "kind": "function", "workflow_step": 1, "summary_override": None},
    {"symbol_name": "generate_dq_rule_candidates_with_fabric_ai", "module": "data_quality", "kind": "function", "workflow_step": 8, "summary_override": None},
    {"symbol_name": "generate_governance_candidates_with_fabric_ai", "module": "data_governance", "kind": "function", "workflow_step": 9, "summary_override": None},
    {"symbol_name": "generate_handover_summary_with_fabric_ai", "module": "handover_documentation", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "check_schema_drift", "module": "data_drift", "kind": "function", "workflow_step": 4, "summary_override": None},
    {"symbol_name": "check_partition_drift", "module": "data_drift", "kind": "function", "workflow_step": 4, "summary_override": None},
    {"symbol_name": "check_profile_drift", "module": "data_drift", "kind": "function", "workflow_step": 4, "summary_override": None},
    {"symbol_name": "summarize_drift_results", "module": "data_drift", "kind": "function", "workflow_step": 4, "summary_override": None},
    {"symbol_name": "classify_column", "module": "data_governance", "kind": "function", "workflow_step": 9, "summary_override": None},
    {"symbol_name": "classify_columns", "module": "data_governance", "kind": "function", "workflow_step": 9, "summary_override": None},
    {"symbol_name": "build_governance_classification_records", "module": "data_governance", "kind": "function", "workflow_step": 9, "summary_override": None},
    {"symbol_name": "write_governance_classifications", "module": "data_governance", "kind": "function", "workflow_step": 9, "summary_override": None},
    {"symbol_name": "summarize_governance_classifications", "module": "data_governance", "kind": "function", "workflow_step": 9, "summary_override": None},
    {"symbol_name": "build_lineage_records", "module": "data_lineage", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "scan_notebook_lineage", "module": "data_lineage", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "scan_notebook_cells", "module": "data_lineage", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "enrich_lineage_steps_with_ai", "module": "data_lineage", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "fallback_copilot_lineage_prompt", "module": "data_lineage", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "validate_lineage_steps", "module": "data_lineage", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "build_lineage_record_from_steps", "module": "data_lineage", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "build_lineage_from_notebook_code", "module": "data_lineage", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "build_lineage_handover_markdown", "module": "data_lineage", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "plot_lineage_steps", "module": "data_lineage", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "build_run_summary", "module": "handover_documentation", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "render_run_summary_markdown", "module": "handover_documentation", "kind": "function", "workflow_step": 10, "summary_override": None},
    {"symbol_name": "build_dataset_run_record", "module": "data_product_metadata", "kind": "function", "workflow_step": 7, "summary_override": None},
    {"symbol_name": "build_schema_snapshot_records", "module": "data_product_metadata", "kind": "function", "workflow_step": 4, "summary_override": None},
    {"symbol_name": "build_schema_drift_records", "module": "data_product_metadata", "kind": "function", "workflow_step": 4, "summary_override": None},
    {"symbol_name": "build_quality_result_records", "module": "data_product_metadata", "kind": "function", "workflow_step": 7, "summary_override": None},
    {"symbol_name": "write_metadata_records", "module": "data_product_metadata", "kind": "function", "workflow_step": 7, "summary_override": None},
    {"symbol_name": "write_multiple_metadata_outputs", "module": "data_product_metadata", "kind": "function", "workflow_step": 7, "summary_override": None},
    {"symbol_name": "load_data_contract", "module": "data_contracts", "kind": "function", "workflow_step": 3, "summary_override": None},
    {"symbol_name": "run_data_product", "module": "data_quality", "kind": "function", "workflow_step": "6A", "summary_override": "Run the starter kit workflow end-to-end for a data product outcome."},
    {"symbol_name": "default_technical_columns", "module": "technical_audit_columns", "kind": "function", "workflow_step": "6B", "summary_override": None},
    {"symbol_name": "add_datetime_features", "module": "technical_audit_columns", "kind": "function", "workflow_step": "6B", "summary_override": None},
    {"symbol_name": "add_audit_columns", "module": "technical_audit_columns", "kind": "function", "workflow_step": "6B", "summary_override": None},
    {"symbol_name": "add_hash_columns", "module": "technical_audit_columns", "kind": "function", "workflow_step": "6B", "summary_override": None},
    {"symbol_name": "normalize_contract_dict", "module": "data_contracts", "kind": "function", "workflow_step": 3, "summary_override": None},
    {"symbol_name": "validate_contract_dict", "module": "data_contracts", "kind": "function", "workflow_step": 3, "summary_override": None},
    {"symbol_name": "build_contract_header_record", "module": "data_contracts", "kind": "function", "workflow_step": 7, "summary_override": None},
    {"symbol_name": "build_contract_column_records", "module": "data_contracts", "kind": "function", "workflow_step": 7, "summary_override": "Build normalized contract-column metadata records for persistence."},
    {"symbol_name": "build_contract_rule_records", "module": "data_contracts", "kind": "function", "workflow_step": 7, "summary_override": "Build quality-rule metadata records from a validated contract."},
    {"symbol_name": "build_contract_records", "module": "data_contracts", "kind": "function", "workflow_step": 7, "summary_override": "Build grouped contract header, column, and rule metadata payloads."},
    {"symbol_name": "contract_records_to_spark", "module": "data_contracts", "kind": "function", "workflow_step": 7, "summary_override": None},
    {"symbol_name": "write_contract_to_lakehouse", "module": "data_contracts", "kind": "function", "workflow_step": 7, "summary_override": "Validate and persist contract records into Fabric metadata tables."},
    {"symbol_name": "load_contract_from_lakehouse", "module": "data_contracts", "kind": "function", "workflow_step": 3, "summary_override": "Load one contract by ID/version from Fabric metadata storage."},
    {"symbol_name": "load_latest_approved_contract", "module": "data_contracts", "kind": "function", "workflow_step": 3, "summary_override": "Load the latest approved contract for a dataset/object pair."},
    {"symbol_name": "extract_required_columns", "module": "data_contracts", "kind": "function", "workflow_step": 3, "summary_override": "Extract required column names from a normalized contract."},
    {"symbol_name": "extract_optional_columns", "module": "data_contracts", "kind": "function", "workflow_step": 3, "summary_override": "Extract optional column names from a normalized contract."},
    {"symbol_name": "extract_business_keys", "module": "data_contracts", "kind": "function", "workflow_step": 3, "summary_override": "Extract business-key column names from a normalized contract."},
    {"symbol_name": "extract_classifications", "module": "data_contracts", "kind": "function", "workflow_step": 3, "summary_override": "Extract column classification mappings from a normalized contract."},
    {"symbol_name": "extract_quality_rules", "module": "data_contracts", "kind": "function", "workflow_step": 3, "summary_override": "Extract raw quality-rule definitions from a normalized contract."},
    {"symbol_name": "get_executable_quality_rules", "module": "data_contracts", "kind": "function", "workflow_step": "6C", "summary_override": "Return normalized quality rules ready for pipeline enforcement."},
    {"symbol_name": "build_contract_summary", "module": "data_contracts", "kind": "function", "workflow_step": 7, "summary_override": "Build a concise contract summary for reviews and handover."},
]
