"""Metadata registry for generated public API documentation."""

from __future__ import annotations

from typing import NotRequired, TypedDict


class PublicSymbolDocMetadata(TypedDict):
    """Documentation metadata for a public symbol exported in ``__all__``."""

    symbol_name: str
    module: str
    kind: str
    template_notebook: str
    template_segment: str
    workflow_step: NotRequired[int | str | None]  # Deprecated: retained for backward compatibility only.
    role: str
    purpose: NotRequired[str]
    summary_override: str | None






class ModuleDocMetadata(TypedDict):
    """Documentation metadata that drives module navigation and overview generation."""

    module_name: str
    visibility: str
    module_summary: str
    sidebar_group: str
    sidebar_include: bool


MODULE_DOCS_METADATA: list[ModuleDocMetadata] = [
    {"module_name": "config", "visibility": "public", "module_summary": "Owns environment setup, runtime initialization, paths, and notebook-wide configuration.", "sidebar_group": "0. Environment setup", "sidebar_include": True},
    {"module_name": "business_context", "visibility": "public", "module_summary": "Owns business meaning for tables and columns.", "sidebar_group": "1. Governance steward", "sidebar_include": True},
    {"module_name": "data_governance", "visibility": "public", "module_summary": "Owns sensitivity, PII, confidentiality, policy labels, and governance approval evidence.", "sidebar_group": "1. Governance steward", "sidebar_include": True},
    {"module_name": "data_profiling", "visibility": "public", "module_summary": "Owns deterministic profiling evidence such as schema, nulls, distincts, min/max, and samples.", "sidebar_group": "2. Analyst / data scientist", "sidebar_include": True},
    {"module_name": "data_quality", "visibility": "public", "module_summary": "Owns DQ rule drafting, review, enforcement, quarantine, and quality results.", "sidebar_group": "2. Analyst / data scientist", "sidebar_include": True},
    {"module_name": "fabric_input_output", "visibility": "public", "module_summary": "Owns Fabric read/write helpers for Lakehouse, Warehouse, and file/table IO.", "sidebar_group": "3. Data engineer", "sidebar_include": True},
    {"module_name": "technical_columns", "visibility": "public", "module_summary": "Owns standard output/audit columns for pipeline outputs.", "sidebar_group": "3. Data engineer", "sidebar_include": True},
    {"module_name": "data_lineage", "visibility": "public", "module_summary": "Owns source-to-target lineage and transformation evidence.", "sidebar_group": "3. Data engineer", "sidebar_include": True},
    {"module_name": "drift", "visibility": "public", "module_summary": "Owns schema/profile/data drift checks as engineering guardrails during pipeline runs.", "sidebar_group": "3. Data engineer", "sidebar_include": True},
    {"module_name": "handover", "visibility": "public", "module_summary": "Owns generated maintainer-facing handover and contract narrative output.", "sidebar_group": "4. Handover / data contract", "sidebar_include": True},
    {"module_name": "metadata", "visibility": "public", "module_summary": "Owns metadata/contract store access, evidence persistence, agreement metadata, notebook evidence, and contract assembly inputs.", "sidebar_group": "5. Metadata / contract store", "sidebar_include": True},
    {"module_name": "ai", "visibility": "internal", "module_summary": "Internal AI utility surface used by workflow-facing public functions.", "sidebar_group": "Internal", "sidebar_include": False},
    {"module_name": "docs_metadata", "visibility": "internal", "module_summary": "Documentation generation metadata and flow mapping internals.", "sidebar_group": "Internal", "sidebar_include": False},
    {"module_name": "schemas", "visibility": "internal", "module_summary": "Internal schema artifacts used for validation and contracts.", "sidebar_group": "Internal", "sidebar_include": False},
    {"module_name": "_utils", "visibility": "internal", "module_summary": "Internal shared helper utilities.", "sidebar_group": "Internal", "sidebar_include": False},
]


class TemplateFlowSegmentMetadata(TypedDict):
    """Segment metadata for starter template guidance on the reference landing page."""

    title: str
    symbols: list[str]
    text: NotRequired[str]


class TemplateFlowDocMetadata(TypedDict):
    """Starter template metadata used to render the template-first function reference."""

    notebook_key: str
    notebook_label: str
    template_path: str
    segment_intro: str
    segments: list[TemplateFlowSegmentMetadata]


TEMPLATE_FLOW_DOCS: list[TemplateFlowDocMetadata] = [{'notebook_key': '00_env_config',
  'notebook_label': '`00_env_config`',
  'template_path': 'templates/notebooks/00_env_config.ipynb',
  'segment_intro': 'Shared environment bootstrap and validation before exploration or pipeline notebooks run.',
  'segments': [{'title': 'Segment 1: Explain the shared environment role',
                'text': 'Describe what this shared config notebook sets up and what downstream exploration or pipeline notebooks depend '
                        'on.',
                'symbols': []},
               {'title': 'Segment 2: Define environment targets and notebook policy', 'symbols': ['Housepath', 'load_config', 'get_path']},
               {'title': 'Segment 3: Set AI, quality, governance, and lineage defaults', 'symbols': []},
               {'title': 'Segment 4: Assemble and validate framework config', 'symbols': ['load_config']},
               {'title': 'Segment 5: Run startup checks and show resolved paths', 'symbols': ['setup_notebook', 'get_path']}]},
 {'notebook_key': '01_data_agreement',
  'notebook_label': '`01_data_sharing_agreement_<agreement>`',
  'template_path': 'templates/notebooks/01_data_agreement_template.ipynb',
  'segment_intro': 'Captures approved usage, business context, stewardship notes, DQ approvals, governance approvals, and agreement-level '
                   'controls reused by exploration and pipeline notebooks.',
  'segments': [{'title': 'Segment 1: Capture agreement context and approved usage', 'symbols': []},
               {'title': 'Segment 2: Prepare governance input from approved business context', 'symbols': []},
               {'title': 'Segment 3: Suggest AI-assisted PII and sensitivity labels', 'symbols': []},
               {'title': 'Segment 4: Human review and approve governance controls', 'symbols': ['review_governance', 'write_governance']},
               {'title': 'Segment 5: Load approved governance metadata for downstream notebooks', 'symbols': ['load_governance']}]},
 {'notebook_key': '02_ex',
  'notebook_label': '`02_ex_<agreement>_<topic>`',
  'template_path': 'templates/notebooks/02_ex_agreement_topic.ipynb',
  'segment_intro': 'Exploration notebook flow used to profile source data and draft advisory AI outputs for human review.',
  'segments': [{'title': 'Segment 1: Load shared config and runtime', 'symbols': ['setup_notebook', 'load_config', 'get_path']},
               {'title': 'Segment 2: Profile source and capture evidence',
                'symbols': ['read_lakehouse_table', 'read_warehouse_table', 'profile_dataframe']},
               {'title': 'Segment 3: AI-assisted drafting (advisory only)',
                'symbols': ['draft_dq_rules', 'review_dq_rules', 'write_dq_rules']},
               {'title': 'Segment 4: Human review and write approved DQ rules', 'symbols': ['write_dq_rules']},
               {'title': 'Optional lineage notes', 'symbols': []}]},
 {'notebook_key': '03_pc',
  'notebook_label': '`03_pc_<agreement>_<pipeline>`',
  'template_path': 'templates/notebooks/03_pc_agreement_source_to_target.ipynb',
  'segment_intro': 'Pipeline notebook flow for deterministic enforcement and controlled publishing.',
  'segments': [{'title': 'Segment 1: Load shared config and runtime context', 'symbols': ['setup_notebook', 'load_config', 'get_path']},
               {'title': 'Segment 2: Load source data and validate required columns',
                'symbols': ['read_lakehouse_table', 'read_warehouse_table']},
               {'title': 'Segment 3: Transform and apply runtime standards', 'symbols': ['standardize_columns', 'validate_dq_rules']},
               {'title': 'Segment 4: Run DQ, split outputs, and publish',
                'symbols': ['enforce_dq', 'assert_dq_passed', 'write_lakehouse_table', 'write_warehouse_table']},
               {'title': 'Optional profiling, drift, governance, lineage, and handover',
                'symbols': ['profile_dataframe',
                            'check_schema_drift',
                            'check_partition_drift',
                            'check_profile_drift',
                            'summarize_drift_results',
                            'write_governance',
                            'write_governance',
                            'load_governance',
                            'build_lineage_records',
                            'build_lineage_handover_markdown',
                            'build_handover',
                            'render_handover_markdown']}]}]
WORKFLOW_STEP_DOCS: list[dict[str, int | str]] = [
    {"number": 1, "slug": "step-01-governance-context", "title": "Governance context", "subtext": "This step captures the governance context: approved usage, owner, and data agreement. The agreement may live outside Fabric, such as in SharePoint documents. Functions in this step mainly link notebooks back to that agreement so the technical work stays tied to the approved business context."},
    {"number": "2A", "slug": "step-02a-shared-runtime-config", "title": "Create shared runtime config", "subtext": "This step creates the shared config that other notebooks depend on, including environment paths, workspace targets, AI availability, and standard naming rules. The goal is to define the project setup once so exploration and pipeline notebooks do not repeat hidden manual configuration."},
    {"number": "2B", "slug": "step-02b-notebook-startup-checks", "title": "Run notebook startup checks", "subtext": "This step runs the startup utility or smoke test at the beginning of every exploration and pipeline notebook. The goal is to confirm the notebook is running in the expected environment, follows naming rules, and has the required Fabric or AI capabilities before any data work begins."},
    {"number": 3, "slug": "step-03-source-contract-ingestion-pattern", "title": "Define source metadata & ingestion pattern", "subtext": "This step defines source metadata expectations between the upstream source and this notebook. It captures what data is expected, including schema, data types, update frequency, update method, watermark column, and whether the source is append only, overwritten, or slowly changing. Functions in this step help the pipeline decide how to ingest, validate, snapshot, or incrementally process source data using approved metadata tables."},
    {"number": 4, "slug": "step-04-ingest-profile-store", "title": "Ingest, profile & store source data", "subtext": "This step brings the source data into the framework, profiles it, and stores it for later use. Functions in this step focus on reading the data, capturing basic profiling results, and saving the raw or source-aligned version before business transformation begins."},
    {"number": 5, "slug": "step-05-explore-transform-logic", "title": "Explore data & explain transformation logic", "subtext": "This step is where the analyst studies the profiled source data and explains why transformation is needed. There may not be many helper functions here today, but future functions could support standard EDA, AI assisted analysis, and documentation of business assumptions before the logic becomes part of the repeatable pipeline."},
    {"number": "6A", "slug": "step-06a-transformation-logic", "title": "Write transformation logic", "subtext": "This step contains the main transformation logic that converts source-aligned data into the target output. Functions here support reusable pipeline code so the same logic can run consistently during development, testing, and scheduled refresh."},
    {"number": "6B", "slug": "step-06b-runtime-standards", "title": "Apply runtime standards", "subtext": "This step applies standard runtime requirements such as technical columns, run IDs, timestamps, partition keys, and other repeatable conventions. Functions here make outputs easier to audit, troubleshoot, join back to pipeline runs, and operate at scale."},
    {"number": "6C", "slug": "step-06c-pipeline-controls", "title": "Enforce pipeline controls", "subtext": "This step enforces the controls that decide whether the pipeline output should be trusted. Functions here support data quality rules, schema checks, classification checks, and other approved metadata validations before data is released downstream."},
    {"number": "6D", "slug": "step-06d-controlled-outputs", "title": "Write controlled outputs", "subtext": "This step writes the transformed output to the correct lakehouse, warehouse, or product layer. Functions here make the write pattern explicit, repeatable, and aligned to the intended environment instead of relying on ad hoc exports."},
    {"number": 7, "slug": "step-07-output-profile-product-contract", "title": "Profile output & publish handover metadata", "subtext": "This step profiles the created output and stores handover metadata for downstream users. Functions here record what was produced, write evidence to metadata tables or catalogues, and keep outputs understandable and reusable downstream."},
    {"number": 8, "slug": "step-08-ai-assisted-dq-suggestions", "title": "Suggest AI assisted data quality rules", "subtext": "This step uses AI in exploration notebooks to suggest possible data quality rules from profiling results, business context, and source knowledge. These AI functions are only advisory. The actual rule creation, approval, and enforcement must still be done by the human engineer in the pipeline notebook."},
    {"number": 9, "slug": "step-09-ai-assisted-classification", "title": "Suggest AI assisted column classification", "subtext": "This step uses AI in exploration notebooks to suggest column classifications such as PII, sensitivity level, and governance labels for the planned output. These AI functions are only advisory. The actual label assignment must be approved by governance or data stewards and enforced by the human engineer in the pipeline notebook."},
    {"number": 10, "slug": "step-10-lineage-handover-documentation", "title": "Generate lineage & handover documentation", "subtext": "This step creates the final documentation needed for review, handover, and future maintenance. Functions here support lineage, transformation summaries, and handover notes so another analyst or engineer can understand what was built, why it was built, and how to operate it."},
]

PUBLIC_SYMBOL_DOCS: list[PublicSymbolDocMetadata] = [{'symbol_name': 'load_config',
  'module': 'config',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'setup_notebook',
  'module': 'config',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'get_path',
  'module': 'config',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'load_agreements',
  'module': 'data_agreement',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': 'Load latest distinct agreement metadata rows for widget selection.'},
 {'symbol_name': 'select_agreement',
  'module': 'data_agreement',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': 'Render a widget dropdown and store selected agreement metadata row in module state.'},
 {'symbol_name': 'get_selected_agreement',
  'module': 'data_agreement',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'register_current_notebook',
  'module': 'metadata',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': 'Register current notebook metadata evidence for agreement traceability.'},
 {'symbol_name': 'load_notebook_registry',
  'module': 'metadata',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': 'Load notebook registration metadata rows for agreement notebook traceability.'},
 {'symbol_name': 'read_lakehouse_table',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'write_lakehouse_table',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'read_warehouse_table',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'write_warehouse_table',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'profile_dataframe',
  'module': 'data_profiling',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'draft_business_context',
  'module': 'business_context',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'review_business_context',
  'module': 'business_context',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'write_business_context',
  'module': 'business_context',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'draft_dq_rules',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'review_dq_rules',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'get_dq_review_results',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'write_dq_rules',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'load_dq_rules',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'enforce_dq',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'assert_dq_passed',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'draft_governance',
  'module': 'data_governance',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'review_governance',
  'module': 'data_governance',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'write_governance',
  'module': 'data_governance',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'load_governance',
  'module': 'data_governance',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'standardize_columns',
  'module': 'technical_columns',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'build_lineage_records',
  'module': 'data_lineage',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'build_lineage_handover_markdown',
  'module': 'data_lineage',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'build_handover',
  'module': 'handover',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'render_handover_markdown',
  'module': 'handover',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'essential',
  'summary_override': None},
 {'symbol_name': 'read_lakehouse_csv',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'read_lakehouse_parquet',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'read_lakehouse_excel',
  'module': 'fabric_input_output',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'validate_dq_rules',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'review_dq_rule_deactivations',
  'module': 'data_quality',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'check_schema_drift',
  'module': 'drift',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'check_partition_drift',
  'module': 'drift',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'check_profile_drift',
  'module': 'drift',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'summarize_drift_results',
  'module': 'drift',
  'kind': 'function',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None},
 {'symbol_name': 'Housepath',
  'module': 'fabric_input_output',
  'kind': 'class',
  'template_notebook': '—',
  'template_segment': '—',
  'role': 'optional',
  'summary_override': None}]
